apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-k8s-fundamentals
spec:
  title: Kubernetes Fundamentals
  description: An interactive workshop on Kubernetes fundamentals.
  content:
    files: imgpkg+http://registry.default.svc.cluster.local:5001/lab-k8s-fundamentals-files:latest
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
